In [1]:
import noise_lib as noise
import torch

In [2]:
lin = noise.LinearScheduler()
loglin = noise.LogLinearNoise()

In [3]:
t = torch.rand(10)

In [4]:
print(lin(t, beta=True, dbeta=True))
print(loglin(t))
print(lin(torch.tensor(1), beta=True, dbeta=True))
print(loglin(torch.tensor(1)))

(tensor([0.1558, 0.2787, 0.6942, 0.4146, 0.8383, 1.6981, 1.5362, 4.9611, 1.0620,
        2.1588]), tensor([  1.1683,   1.3211,   2.0018,   1.5134,   2.3120,   5.4622,   4.6458,
        142.7277,   2.8916,   8.6590]))
(tensor([0.1555, 0.2783, 0.6932, 0.4140, 0.8370, 1.6939, 1.5328, 4.8410, 1.0602,
        2.1518]), tensor([  1.1671,   1.3196,   1.9982,   1.5113,   2.3072,   5.4355,   4.6264,
        126.4652,   2.8841,   8.5920]))
(tensor(9.2103), tensor(9998.0010))
(tensor(6.9078), tensor(999.0129))


In [5]:
x = torch.rand(1, 10, 4)
indices = torch.randint(0, 4, (1, 10))
print(x)
print(indices)
x = torch.scatter(x, -1, indices[..., None], torch.zeros_like(x[..., :1]))
print(x)

tensor([[[0.8668, 0.4040, 0.0088, 0.2288],
         [0.1743, 0.7855, 0.7190, 0.7696],
         [0.8698, 0.1853, 0.3008, 0.6823],
         [0.2253, 0.8633, 0.1385, 0.5825],
         [0.6496, 0.6449, 0.4059, 0.9445],
         [0.1519, 0.6850, 0.7111, 0.5642],
         [0.0538, 0.1374, 0.5368, 0.9450],
         [0.8430, 0.5064, 0.1835, 0.0333],
         [0.3901, 0.4026, 0.4167, 0.2508],
         [0.3853, 0.5700, 0.1396, 0.9623]]])
tensor([[3, 1, 2, 0, 0, 3, 3, 2, 3, 3]])
tensor([[[0.8668, 0.4040, 0.0088, 0.0000],
         [0.1743, 0.0000, 0.7190, 0.7696],
         [0.8698, 0.1853, 0.0000, 0.6823],
         [0.0000, 0.8633, 0.1385, 0.5825],
         [0.0000, 0.6449, 0.4059, 0.9445],
         [0.1519, 0.6850, 0.7111, 0.0000],
         [0.0538, 0.1374, 0.5368, 0.0000],
         [0.8430, 0.5064, 0.0000, 0.0333],
         [0.3901, 0.4026, 0.4167, 0.0000],
         [0.3853, 0.5700, 0.1396, 0.0000]]])
