In [1]:
import noise_lib as noise
import torch

In [2]:
lin = noise.LinearScheduler()
loglin = noise.LogLinearNoise()

AttributeError: module 'noise_lib' has no attribute 'LogLinearNoise'

In [ ]:
t = torch.rand(10)

In [ ]:
print(lin(t))
print(loglin(t))

In [4]:
x = torch.rand(1, 10, 4)
indices = torch.randint(0, 4, (1, 10))
print(x)
print(indices)
x = torch.scatter(x, -1, indices[..., None], torch.zeros_like(x[..., :1]))
print(x)

tensor([[[0.7203, 0.5053, 0.4941, 0.5619],
         [0.2747, 0.1647, 0.3684, 0.7579],
         [0.8783, 0.5932, 0.8331, 0.8432],
         [0.8175, 0.7256, 0.3571, 0.3283],
         [0.3813, 0.2622, 0.6627, 0.6528],
         [0.2288, 0.3083, 0.5572, 0.0766],
         [0.8380, 0.3457, 0.1197, 0.9616],
         [0.3713, 0.6574, 0.5857, 0.0202],
         [0.7191, 0.7085, 0.1949, 0.3752],
         [0.0601, 0.8544, 0.5920, 0.5702]]])
tensor([[3, 2, 0, 3, 0, 0, 2, 1, 2, 0]])
tensor([[[0.7203, 0.5053, 0.4941, 0.0000],
         [0.2747, 0.1647, 0.0000, 0.7579],
         [0.0000, 0.5932, 0.8331, 0.8432],
         [0.8175, 0.7256, 0.3571, 0.0000],
         [0.0000, 0.2622, 0.6627, 0.6528],
         [0.0000, 0.3083, 0.5572, 0.0766],
         [0.8380, 0.3457, 0.0000, 0.9616],
         [0.3713, 0.0000, 0.5857, 0.0202],
         [0.7191, 0.7085, 0.0000, 0.3752],
         [0.0000, 0.8544, 0.5920, 0.5702]]])
